---
abstract: 'Wrapper for flock() to make file locking trivial'
author:
  - 'David Muir Sharnoff <cpan@dave.sharnoff.org>'
build_requires:
  File::Slurp: 0
  Test::SharedFork: 0
  Time::HiRes: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Flock
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 0
  Data::Structure::Util: 0
  IO::Event: 0.809
  Time::HiRes: 0
resources:
  repository: http://github.com/muir/File-Flock
version: 2013.06
